### ISSUE TITLE
consider using wl_display_dispatch() instead of wl_diplsay_roundtrip()

### ISSUE THREAD

**Issue by rcubee** [kdchambers/vkwayland#1]
https://github.com/kdchambers/vkwayland/blob/344eec73536db45c409c2bda8c4225911324a5b0/src/main.zig#L660
I think that you may want to call wl_display_dispatch or wl_display_dispatch_pending instead of wl_diplsay_roundtrip in the main loop of your app.

**Comment by kdchambers** [comment]
Thanks for the comment! That does seem correct but it appears like I would have to implement reading events from the compositor manually.  If you just swap out `roundtrip` as-is, none of the listeners get invoked (E.g The screen gets stuck at it's initial size).

I'll look into it this week if I have time and see can I write a better loop implementation using more primitive wayland functionality. Fair to leave this issue open until then as something more fine grained than roundtrip should be used in the loop.
